# GraphQL Configuration
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.schema.printer.enabled=true
spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-methods=GET,POST,OPTIONS
spring.graphql.cors.allowed-headers=*
spring.graphql.cors.allow-credentials=true
spring.graphql.cors.max-age=1800

# Spring Boot Application
spring.application.name=tt-data-league-api-graphql

